"""fourth migration

Revision ID: 427a0a42d3c8
Revises: 6fdf52828365
Create Date: 2024-03-26 12:06:25.982351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427a0a42d3c8'
down_revision = '6fdf52828365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
