"""initial migration

Revision ID: 5dbf086a8199
Revises: 
Create Date: 2024-03-26 22:25:41.738448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5dbf086a8199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False))

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('score')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
