"""third migration

Revision ID: 6fdf52828365
Revises: a572cf8a6d50
Create Date: 2024-03-24 13:27:11.296941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fdf52828365'
down_revision = 'a572cf8a6d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
